<a href="https://colab.research.google.com/github/Charishmaaaa/demo/blob/main/icp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
random_vector = np.random.randint(1, 21, size=15)
reshaped_array = random_vector.reshape(3, 5)
print("Original Array:")
print(reshaped_array)
reshaped_array[np.arange(3), np.argmax(reshaped_array, axis=1)] = 0
print("\nModified Array:")
print(reshaped_array)


Original Array:
[[ 7 12  5  8 14]
 [ 4 20 14 15  7]
 [ 9 20 14 18  2]]

Modified Array:
[[ 7 12  5  8  0]
 [ 4  0 14 15  7]
 [ 9  0 14 18  2]]


In [3]:
import numpy as np
array_2d = np.empty((4, 3), dtype=np.int32)
print("Shape of the array:", array_2d.shape)
print("Type of the array:", type(array_2d))
print("Data type of the array:", array_2d.dtype)


Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [4]:
import numpy as np
arr = np.array([[0, 1, 2],
                [3, 4, 5]])
diagonal_sum = np.trace(arr)
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [6]:
import numpy as np
odd_numbers = np.arange(11, 71, 2)
even_numbers = np.arange(10, 71, 2)

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

array = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])

sorted_by_row = np.sort(array, axis=1)

sorted_by_column = np.sort(array, axis=0)
print("Task A:")
print("Odd Numbers:", odd_numbers)
print("Even Numbers:", even_numbers)

print("\nTask B:")
print("Array1:", array1)
print("Array2:", array2)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)

print("\nTask C:")
print("Original Array:")
print(array)
print("Sorted by Row:")
print(sorted_by_row)
print("Sorted by Column:")
print(sorted_by_column)


Task A:
Odd Numbers: [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
Even Numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]

Task B:
Array1: [1 2 3]
Array2: [4 5 6]
Addition Result: [5 7 9]
Subtraction Result: [-3 -3 -3]
Multiplication Result: [ 4 10 18]

Task C:
Original Array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Sorted by Row:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Sorted by Column:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [7]:
import numpy as np
data = np.array([[4, 2, np.nan, 1],
                 [11, 12, 14, 9],
                 [5, np.nan, 1, np.nan]])
missing_data_mask = np.isnan(data)
print("Missing Data:")
print(missing_data_mask)


Missing Data:
[[False False  True False]
 [False False False False]
 [False  True False  True]]
